apiVersion: apps/v1
kind: Deployment
metadata:
  name:  spring-mysql
  namespace: default
  labels:
    app:  spring-mysql
spec:
  selector:
    matchLabels:
      app: spring-mysql
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  spring-mysql
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  spring-mysql
        image: mohamman/spring-petclinic-mysql-profile
        env:
        - name: MYSQL_URL
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_url
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_pass
---
apiVersion: v1
kind: Service
metadata:
  name: spring-mysql-svc
  namespace: default
spec:
  selector:
    app: spring-mysql
  type: LoadBalancer
  ports:
  - name: spring-mysql-8080
    protocol: TCP
    port: 80
    targetPort: 8080